version: '2'
services:
  activemq:
    hostname: activemq
    image: webcenter/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    restart: always
    container_name: activemq
  hostel:
    build: .
    ports:
      - '8080:8080'
    links:
      - activemq
    depends_on:
      - activemq