spring:
  liquibase:
    enabled: true
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
    url: jdbc:h2:file:./db
    username: u
    password: 1
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    client:
      clientid: 465667265845-68i6auv961o1p1a44pqquups9ialqg88.apps.googleusercontent.com
      clientSecret: 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
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      authenticationScheme: form
      scope: openid,email,profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true

server:
  port: 8080
